### ISSUE TITLE
Cannot find module "es-get-iterator" with ZEIT

### ISSUE THREAD

**Issue by jasonsilberman** [ljharb/es-get-iterator#5]
Hello,

I am trying to use `firebase-admin` which relies on this package inside a Serverless Function deploying on ZEIT.

I have found [this issue](https://github.com/zeit/ncc/issues/521) on the ZEIT `ncc` repository but have not been able to find any solutions.

When I try to execute the function, I get the following error:
```
[ERROR] Error: Cannot find module 'es-get-iterator'
Require stack:
- <PATH>/api/node_modules/deep-equal/index.js
- <PATH>/api/node_modules/@google-cloud/firestore/build/src/document.js
- <PATH>/api/node_modules/@google-cloud/firestore/build/src/index.js
- <PATH>/api/node_modules/firebase-admin/lib/firebase-namespace.js
- <PATH>/api/node_modules/firebase-admin/lib/default-namespace.js
- <PATH>/api/node_modules/firebase-admin/lib/index.js
- <PATH>/api/_utils/fetchData.js
- <PATH>/api/build.js
- <PATH>/___now_launcher.js
```

If there is anything you could suggest to help get around this issue it would be greatly appreciated.

Thanks!

**Comment by ljharb** [comment]
Since `deep-equal` depends on and requires `es-get-iterator`, the issue would be filed in `deep-equal`, but since it's in package.json, there's nothing to fix.

This is something I'd file on zeit, since you can see [here](https://unpkg.com/browse/deep-equal@2.0.2/package.json) that `es-get-iterator` is listed.

**Comment by ljharb** [comment]
Please link me to the issue when you file it; i want to follow it and make sure there's nothing that deep-equal or es-get-iterator need to fix.

**Comment by jgehrcke** [comment]
> Please link me to the issue when you file it

@ljharb just making sure that you've seen https://github.com/vercel/ncc/issues/521
